# Generated by Django 6.0 on 2025-12-26 21:34

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_chauffeur_actif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarification',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='tarification',
            name='date_modification',
        ),
        migrations.AddField(
            model_name='expedition',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='expedition',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournee',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='date_retour_reelle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='kilometrage_parcouru',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='nom_destinataire',
            field=models.CharField(default='client@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expedition',
            name='telephone_destinataire',
            field=phonenumber_field.modelfields.PhoneNumberField(default='client@gmail.com', help_text='Ex: +213551234567', max_length=128, region='DZ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournee',
            name='kilometrage_depart',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Auto-rempli depuis le véhicule au départ', null=True),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(help_text='Date limite de paiement')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('statut_paiement', models.CharField(choices=[('IMPAYEE', 'Impayée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée intégralement'), ('ANNULEE', 'Annulée')], default='IMPAYEE', max_length=25)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='app1.client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.AddField(
            model_name='expedition',
            name='facture',
            field=models.ForeignKey(blank=True, help_text='Facture à laquelle cette expédition est rattachée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='app1.facture'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_incident', models.CharField(editable=False, max_length=50, unique=True)),
                ('type_incident', models.CharField(choices=[('RETARD', 'Retard de livraison'), ('PERTE', 'Perte de colis'), ('ENDOMMAGEMENT', 'Endommagement'), ('TECHNIQUE', 'Problème technique (véhicule)'), ('ACCIDENT', 'Accident de circulation'), ('METEO', 'Conditions météorologiques'), ('ADRESSE', 'Adresse incorrecte/introuvable'), ('REFUS', 'Refus de réception'), ('AUTRE', 'Autre')], max_length=20)),
                ('gravite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Élevée'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=10)),
                ('titre', models.CharField(help_text="Titre court de l'incident", max_length=200)),
                ('description', models.TextField(help_text="Description détaillée de l'incident")),
                ('lieu_incident', models.CharField(blank=True, help_text="Lieu où l'incident s'est produit", max_length=200, null=True)),
                ('date_incident', models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure de l'incident")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, help_text="Date de création de l'incident")),
                ('date_resolution', models.DateTimeField(blank=True, help_text="Date de résolution de l'incident", null=True)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('CLOS', 'Clos')], default='OUVERT', max_length=15)),
                ('actions_entreprises', models.TextField(blank=True, help_text="Actions entreprises pour résoudre l'incident", null=True)),
                ('solution', models.TextField(blank=True, help_text='Solution apportée', null=True)),
                ('cout_estime', models.DecimalField(blank=True, decimal_places=2, help_text="Coût estimé de l'incident en DA", max_digits=10, null=True)),
                ('document', models.FileField(blank=True, help_text="Document ou photo de l'incident", null=True, upload_to='incidents/%Y/%m/')),
                ('alerte_client_envoyee', models.BooleanField(default=False, help_text='Alerte envoyée au client')),
                ('alerte_direction_envoyee', models.BooleanField(default=False, help_text='Alerte envoyée à la direction')),
                ('remarques', models.TextField(blank=True, null=True)),
                ('agent_rapporteur', models.ForeignKey(blank=True, help_text="Agent qui a rapporté l'incident", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_rapportes', to=settings.AUTH_USER_MODEL)),
                ('agent_responsable', models.ForeignKey(blank=True, help_text="Agent chargé de traiter l'incident", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assignes', to=settings.AUTH_USER_MODEL)),
                ('expedition', models.ForeignKey(blank=True, help_text='Expédition concernée (si applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='app1.expedition')),
                ('tournee', models.ForeignKey(blank=True, help_text='Tournée concernée (si applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='app1.tournee')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date_incident'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paiement', models.CharField(editable=False, max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('VIREMENT', 'Virement postale'), ('CARTE', 'Carte bancaire'), ('CARTE', 'Carte edahabia'), ('MOBILE', 'Paiement mobile'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Validé'), ('EN_ATTENTE', 'En attente de validation'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=15)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='app1.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reclamation', models.CharField(default='REC-0000-0000', editable=False, max_length=50, unique=True)),
                ('nature', models.CharField(choices=[('RETARD', 'Retard de livraison'), ('PERTE', 'Perte de colis'), ('ENDOMMAGEMENT', 'Colis endommagé'), ('ERREUR_FACTURATION', 'Erreur de facturation'), ('MAUVAIS_SERVICE', 'Mauvaise qualité de service'), ('LITIGE_MONTANT', 'Litige sur le montant'), ('NON_LIVRAISON', 'Non-livraison'), ('COMPORTEMENT', 'Comportement du personnel'), ('AUTRE', 'Autre')], default='AUTRE', max_length=25)),
                ('objet', models.CharField(help_text='Objet de la réclamation', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée de la réclamation')),
                ('date_reclamation', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de la réclamation')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_resolution', models.DateTimeField(blank=True, help_text='Date de résolution', null=True)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours de traitement'), ('EN_ATTENTE_CLIENT', 'En attente de réponse client'), ('RESOLUE', 'Résolue'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], default='NOUVELLE', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10)),
                ('reponse', models.TextField(blank=True, help_text='Réponse apportée au client', null=True)),
                ('actions_correctives', models.TextField(blank=True, help_text='Actions correctives mises en place', null=True)),
                ('compensation_accordee', models.BooleanField(default=False, help_text='Compensation accordée au client')),
                ('montant_compensation', models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la compensation en DA', max_digits=10, null=True)),
                ('type_compensation', models.CharField(blank=True, help_text='Type de compensation (remboursement, avoir, geste commercial...)', max_length=100, null=True)),
                ('client_satisfait', models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non'), ('SANS_REPONSE', 'Sans réponse')], help_text='Le client est-il satisfait de la résolution?', max_length=15, null=True)),
                ('document', models.FileField(blank=True, help_text='Document joint par le client', null=True, upload_to='reclamations/%Y/%m/')),
                ('remarques', models.TextField(blank=True, null=True)),
                ('agent_responsable', models.ForeignKey(blank=True, help_text='Agent chargé de traiter la réclamation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_assignees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='app1.client')),
                ('expedition', models.ForeignKey(blank=True, help_text='Expédition concernée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='app1.expedition')),
                ('facture', models.ForeignKey(blank=True, help_text='Facture concernée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='app1.facture')),
                ('incident', models.ForeignKey(blank=True, help_text='Incident lié (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='app1.incident')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_reclamation'],
            },
        ),
    ]
